site_name: CCT Expérience
theme:
  name: dsfr
  locale: fr

plugins:
  - search:
      lang: fr
  - open-in-new-tab
  - tags_index
  - rss
  - git-revision-date-localized:
     fallback_to_build_date: true
  - dsfr_base

markdown_extensions:
  - dsfr_structure.extension.all_extensions
  - pymdownx.snippets
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.emoji:
      options:
        attributes:
          align: absmiddle
          height: 20px
          width: 20px
  - pymdownx.superfences
  - toc:
      permalink: false
      toc_depth: 2
  - attr_list
  - def_list
  - tables

